In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


df = pd.read_csv('data.csv')
df = df.iloc[np.random.permutation(len(df))]
y = df.iloc[0:100, 4].values
y = np.where(y == "Iris-setosa", 1, -1)
X = df.iloc[0:100, [0, 2]].values


inputSize = X.shape[1] # количество входных сигналов равно количеству признаков задачи 
hiddenSizes = 10 # задаем число нейронов скрытого (А) слоя 
outputSize = 1 if len(y.shape) else y.shape[1] # количество выходных сигналов равно количеству классов задачи


# создаем матрицу весов скрытого слоя
Win = np.zeros((1+inputSize,hiddenSizes)) 
# пороги w0 задаем случайными числами
Win[0,:] = (np.random.randint(0, 3, size = (hiddenSizes))) 
# остальные веса  задаем случайно -1, 0 или 1 
Win[1:,:] = (np.random.randint(-1, 2, size = (inputSize,hiddenSizes))) 

#Wout = np.zeros((1+hiddenSizes,outputSize))

# случайно инициализируем веса выходного слоя
Wout = np.random.randint(0, 2, size = (1+hiddenSizes,outputSize)).astype(np.float64)
   
# функция прямого прохода (предсказания) 
def predict(Xp):
    # выходы первого слоя = входные сигналы * веса первого слоя
    hidden_predict = np.where((np.dot(Xp, Win[1:,:]) + Win[0,:]) >= 0.0, 1, -1).astype(np.float64)
    # выходы второго слоя = выходы первого слоя * веса второго слоя
    out = np.where((np.dot(hidden_predict, Wout[1:,:]) + Wout[0,:]) >= 0.0, 1, -1).astype(np.float64)
    return out, hidden_predict


# обучение
# у перцептрона Розенблата обучаются только веса выходного слоя 
# как и раньше обучаем подавая по одному примеру и корректируем веса в случае ошибки
n_iter=1000
eta = 0.01

# переменные для сравнения весов и ошибок
prev_Wout = None
errors = []

border_equal = 0

for i in range(n_iter):
    error_count = 0
    for xi, target, j in zip(X, y, range(X.shape[0])):
        pr, hidden = predict(xi) 
        error = target - pr
        if error != 0:
            error_count += 1
        Wout[1:] += ((eta * error) * hidden).reshape(-1, 1)
        Wout[0] += eta * error
    
    # условие остановки: ошибок нет
    if error_count == 0:
        print(f"Обучение завершено, ошибок нет на итерации {i}")
        break

    # условие остановки: веса не меняются
    if np.array_equal(prev_Wout, Wout):
        print(f"Сходимость достигнута на итерации {i}")
        break


    # сохраняем веса и количество ошибок для следующей итерации
    prev_Wout = Wout.copy()
    errors.append(error_count)

# посчитаем сколько ошибок делаем на всей выборке
y = df.iloc[:, 4].values
y = np.where(y == "Iris-setosa", 1, -1)
X = df.iloc[:, [0, 2]].values
pr, hidden = predict(X)
sum(pr-y.reshape(-1, 1))


Обучение завершено, ошибок нет на итерации 1


array([0.])

In [8]:
print(prev_Wout)
print(Wout)


[[-0.1]
 [-0.1]
 [ 0.9]
 [ 0.9]
 [ 1.1]
 [-0.1]
 [ 0.9]
 [ 1.1]
 [ 0.9]
 [ 0.1]
 [ 1.1]]
[[-0.1]
 [-0.1]
 [ 0.9]
 [ 0.9]
 [ 1.1]
 [-0.1]
 [ 0.9]
 [ 1.1]
 [ 0.9]
 [ 0.1]
 [ 1.1]]
